// Copyright Twilio Inc. <open-source@twilio.com> (https://www.twilio.com/docs/verify/push) 2021. All Rights Reserved.
// Node module: twilio-verify-for-react-native
// This file is licensed under the Apache License 2.0.
// License text available at https://github.com/twilio/twilio-verify-for-react-native/blob/main/LICENSE

import PushNotification, {
  Importance,
  ReceivedNotification,
} from 'react-native-push-notification';
import NotificationHandler from './NotificationHandler';

export default class NotificationService {
  lastId = 0;

  constructor(
    onRegister: (token: { os: string; token: string }) => void,
    onNotification: (
      notification: Omit<ReceivedNotification, 'userInfo'>
    ) => void
  ) {
    this.createDefaultChannels();

    NotificationHandler.attachRegister(onRegister);
    NotificationHandler.attachNotification(onNotification);

    // Clear badge number at start
    PushNotification.getApplicationIconBadgeNumber(function (number) {
      if (number > 0) {
        PushNotification.setApplicationIconBadgeNumber(0);
      }
    });
  }

  createDefaultChannels() {
    PushNotification.createChannel(
      {
        channelId: 'default-channel-id', // (required)
        channelName: `Default channel`, // (required)
        channelDescription: 'A default channel', // (optional) default: undefined.
        soundName: 'default', // (optional) See `soundName` parameter of `localNotification` function
        importance: Importance.HIGH, // (optional) default: Importance.HIGH. Int value of the Android notification importance
        vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
      },
      (created) =>
        console.log(`createChannel 'default-channel-id' returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
    );
  }

  localNotification(payload: Record<string, any>) {
    this.lastId++;
    PushNotification.localNotification({
      /* Android Only Properties */
      channelId: 'default-channel-id',
      autoCancel: true, // (optional) default: true
      largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
      smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
      ignoreInForeground: true,

      /* iOS and Android properties */
      id: this.lastId, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      title: 'New challenge', // (optional)
      message: payload.message, // (required)
      userInfo: payload, // (optional) default: {} (using null throws a JSON value '<null>' error)
      number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      playSound: false,
    });
  }
}
