# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RNTwilioVerify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNTwilioVerify
  pod 'TwilioVerify', :git => 'https://github.com/twilio/twilio-verify-ios.git', :branch => 'ymoreno/read-sdk-version'
  #pod 'TwilioVerify', '~> 0.2.0'
end
